INSERT INTO user.users (id, username, password) VALUES (1, "user1", "pass1");
INSERT INTO user.users (id, username, password) VALUES (2, "user2", "pass2");
INSERT INTO user.users (id, username, password) VALUES (3, "user3", "pass3");
INSERT INTO user.users (id, username, password) VALUES (4, "user4", "pass4");
INSERT INTO user.users (id, username, password) VALUES (5, "user5", "pass5");
INSERT INTO user.users (id, username, password) VALUES (6, "user6", "pass6");
INSERT INTO user.users (id, username, password) VALUES (7, "user7", "pass7");
INSERT INTO user.users (id, username, password) VALUES (8, "user8", "pass8");
INSERT INTO user.users (id, username, password) VALUES (9, "user10", "@@@@@");
